INSERT IGNORE INTO projects.projects (id, project_name)
VALUES (1, 'Startup Project'),
       (2, 'Online Banking'),
       (3, 'Flight Booking'),
       (4, 'Ticket System'),
       (5, 'E-HealthCare Management'),
       (6, 'Electricity Billing System'),
       (7, 'Online Survey System'),
       (8, 'E-Commerce Software'),
       (9, 'Smart-City Project'),
       (10, 'Book Shop'),
       (15, 'Manage ToDos App'),
       (23, 'Jedi Galaxy Online Game'),
       (27, 'Facial Recognition'),
       (31, 'Personal Blog');

INSERT IGNORE INTO projects.employee (id, first_name, last_name)
VALUES (1, 'Yordan', 'Kondov'),
       (2, 'Ivan', 'Ivanov'),
       (3, 'Petar', 'Nikolaev'),
       (4, 'Maria', 'Angelova'),
       (5, 'Nadezhda', 'Petrova'),
       (6, 'Teodora', 'Todorova'),
       (7, 'Dimitar', 'Pavlov'),
       (8, 'Nikola', 'Stoilov'),
       (9, 'Hristo', 'Ivanov'),
       (10, 'Daniel', 'Hristov'),
       (11, 'Ani', 'Stoilova'),
       (12, 'Rumyana', 'Panayotova'),
       (13, 'Mariyan', 'Stanev'),
       (14, 'Naria-Antoaneta', 'Lalova'),
       (15, 'Angel', 'Marinov'),
       (21, 'Bozhko', 'Benovski'),
       (27, 'Qnko', 'Sokolov'),
       (38, 'Hristina', 'Georgieva'),
       (42, 'Viktor', 'Kalev'),
       (58, 'Roska', 'Parvanova'),
       (65, 'Dimo', 'Ivanov'),
       (78, 'Monika', 'Taneva');